# Docker Compose for local testing
# Use this to test your Kestra setup locally before deploying to Koyeb

version: '3.8'

services:
  kestra:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Same environment variables as Koyeb deployment
      KESTRA_REPOSITORY_TYPE: memory
      KESTRA_STORAGE_TYPE: local
      KESTRA_STORAGE_LOCAL_BASE_PATH: /tmp/kestra-storage
      KESTRA_QUEUE_TYPE: memory
      KESTRA_DATASOURCES_DEFAULT_URL: "jdbc:h2:mem:public;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
      KESTRA_DATASOURCES_DEFAULT_DRIVER_CLASS_NAME: org.h2.Driver
      KESTRA_DATASOURCES_DEFAULT_USERNAME: sa
      KESTRA_DATASOURCES_DEFAULT_PASSWORD: ""
      KESTRA_DATASOURCES_DEFAULT_DIALECT: H2
      MICRONAUT_SERVER_PORT: 8080
      JAVA_OPTS: "-Xmx256m -Xms128m -XX:+UseG1GC"
    volumes:
      # Mount local directories for persistence during development
      - kestra_storage:/tmp/kestra-storage
      - kestra_logs:/tmp/kestra-logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  kestra_storage:
    driver: local
  kestra_logs:
    driver: local

# Networks (optional)
networks:
  default:
    name: kestra-network
