[build]
type = "docker"
dockerfile = "Dockerfile"

[deploy]
ports = [8080]

[deploy.health_check]
path = "/health"
port = 8080
initial_delay_seconds = 60
period_seconds = 30
timeout_seconds = 10
failure_threshold = 3
